### ISSUE TITLE
Make it compatible with CJS

### ISSUE THREAD

**Issue by ngouy** [koddsson/eslint-plugin-tscompat#159]
I wanted to give this plugin a try, the original plugin is exactly what I was looking for but this makes it kinda un-usable at scale:
![image](https://github.com/user-attachments/assets/bdddb4ed-43b1-49db-9a07-daf3b75d710d)

I saw on one issue you developed this alternative just for that. I wanted to give it a try but didn't worked. 

(I have an old eslint.cjs config)
this is my config:
```
// .eslintrc.cjs
module.exports = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "tsconfig.json",
    tsconfigRootDir: __dirname,
    sourceType: "module",
  },
  plugins: [
    "@koddsson/eslint-plugin-tscompat", // 'tscompat' doesn't work
    ...],
   rules: { // doesn't really matter for now }
 };
```

eslint logs:
```
[Error - 9:11:44 AM] Request textDocument/diagnostic failed.
  Message: Request textDocument/diagnostic failed with message: Failed to load plugin '@koddsson/eslint-plugin-tscompat' declared in '.eslintrc.cjs': require() of ES Module /.../node_modules/.pnpm/@koddsson+eslint-plugin-tscompat@0.0.12/node_modules/@koddsson/eslint-plugin-tscompat/index.js from /.../node_modules/.pnpm/@eslint+eslintrc@1.4.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of index.js in /.../node_modules/.pnpm/@eslint+eslintrc@1.4.1/node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
```

**Comment by koddsson** [comment]
Hey thanks for the issue. 

>I wanted to give this plugin a try, the original plugin is exactly what I was looking for but this makes it kinda un-usable at scale:

I'm happy to hear that this plugin seems to solve a issue you are having.

> (I have an old eslint.cjs config)

Have you considered upgrading to ESLint 9 and the flat config that's the new default? All my projects are on ESLint 9 so this plugin was made with that configuration in mind. I'm not quite sure what your options are in any legacy ESLint versions but maybe the [`FlatCompat`](https://github.com/eslint/eslintrc?tab=readme-ov-file#usage-commonjs) utility can help?

With all that being said I don't have any plans on supporting CommonJS as I feel like the added complexity isn't worth the benefits.

**Comment by ngouy** [comment]
@koddsson TY for the answer
I will have to check, but does the new eslint way of building config is compatible with commonJS projects is the question
I will dig in. 
Thanks for the reply, and obviously that's complitely fine. I don't know how hard or not it is so that's why I asked
